/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClientPortalRouteRouteImport } from './routes/client-portal/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ClientPortalIndexRouteImport } from './routes/client-portal/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ClientPortalWalletRouteImport } from './routes/client-portal/wallet'
import { Route as AuthSetPasswordRouteImport } from './routes/auth.set-password'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns.new'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'
import { Route as AuthenticatedAdminFinancialRouteImport } from './routes/_authenticated/admin.financial'
import { Route as ApiPublicWebhooksInterPixRouteImport } from './routes/api/public/webhooks/inter-pix'
import { Route as AuthenticatedClientsIdWalletRouteImport } from './routes/_authenticated/clients.$id.wallet'
import { Route as AuthenticatedClientsIdSocialProfileIdRouteImport } from './routes/_authenticated/clients.$id.social.$profileId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRouteRoute = ClientPortalRouteRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalIndexRoute = ClientPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientPortalRouteRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClientPortalWalletRoute = ClientPortalWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ClientPortalRouteRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFinancialRoute =
  AuthenticatedAdminFinancialRouteImport.update({
    id: '/admin/financial',
    path: '/admin/financial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksInterPixRoute =
  ApiPublicWebhooksInterPixRouteImport.update({
    id: '/api/public/webhooks/inter-pix',
    path: '/api/public/webhooks/inter-pix',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientsIdWalletRoute =
  AuthenticatedClientsIdWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedClientsIdRoute,
  } as any)
const AuthenticatedClientsIdSocialProfileIdRoute =
  AuthenticatedClientsIdSocialProfileIdRouteImport.update({
    id: '/social/$profileId',
    path: '/social/$profileId',
    getParentRoute: () => AuthenticatedClientsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/client-portal': typeof ClientPortalRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/client-portal/wallet': typeof ClientPortalWalletRoute
  '/client-portal/': typeof ClientPortalIndexRoute
  '/admin/financial': typeof AuthenticatedAdminFinancialRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRouteWithChildren
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/clients/$id/wallet': typeof AuthenticatedClientsIdWalletRoute
  '/api/public/webhooks/inter-pix': typeof ApiPublicWebhooksInterPixRoute
  '/clients/$id/social/$profileId': typeof AuthenticatedClientsIdSocialProfileIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/client-portal/wallet': typeof ClientPortalWalletRoute
  '/': typeof AuthenticatedIndexRoute
  '/client-portal': typeof ClientPortalIndexRoute
  '/admin/financial': typeof AuthenticatedAdminFinancialRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRouteWithChildren
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/clients/$id/wallet': typeof AuthenticatedClientsIdWalletRoute
  '/api/public/webhooks/inter-pix': typeof ApiPublicWebhooksInterPixRoute
  '/clients/$id/social/$profileId': typeof AuthenticatedClientsIdSocialProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/client-portal': typeof ClientPortalRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/client-portal/wallet': typeof ClientPortalWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/client-portal/': typeof ClientPortalIndexRoute
  '/_authenticated/admin/financial': typeof AuthenticatedAdminFinancialRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRouteWithChildren
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/clients/$id/wallet': typeof AuthenticatedClientsIdWalletRoute
  '/api/public/webhooks/inter-pix': typeof ApiPublicWebhooksInterPixRoute
  '/_authenticated/clients/$id/social/$profileId': typeof AuthenticatedClientsIdSocialProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-portal'
    | '/auth'
    | '/clients'
    | '/settings'
    | '/auth/set-password'
    | '/client-portal/wallet'
    | '/client-portal/'
    | '/admin/financial'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/clients/$id'
    | '/campaigns/'
    | '/clients/$id/wallet'
    | '/api/public/webhooks/inter-pix'
    | '/clients/$id/social/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/clients'
    | '/settings'
    | '/auth/set-password'
    | '/client-portal/wallet'
    | '/'
    | '/client-portal'
    | '/admin/financial'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/clients/$id'
    | '/campaigns'
    | '/clients/$id/wallet'
    | '/api/public/webhooks/inter-pix'
    | '/clients/$id/social/$profileId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/client-portal'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/settings'
    | '/auth/set-password'
    | '/client-portal/wallet'
    | '/_authenticated/'
    | '/client-portal/'
    | '/_authenticated/admin/financial'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/clients/$id'
    | '/_authenticated/campaigns/'
    | '/_authenticated/clients/$id/wallet'
    | '/api/public/webhooks/inter-pix'
    | '/_authenticated/clients/$id/social/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClientPortalRouteRoute: typeof ClientPortalRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicWebhooksInterPixRoute: typeof ApiPublicWebhooksInterPixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal/': {
      id: '/client-portal/'
      path: '/'
      fullPath: '/client-portal/'
      preLoaderRoute: typeof ClientPortalIndexRouteImport
      parentRoute: typeof ClientPortalRouteRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/client-portal/wallet': {
      id: '/client-portal/wallet'
      path: '/wallet'
      fullPath: '/client-portal/wallet'
      preLoaderRoute: typeof ClientPortalWalletRouteImport
      parentRoute: typeof ClientPortalRouteRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/financial': {
      id: '/_authenticated/admin/financial'
      path: '/admin/financial'
      fullPath: '/admin/financial'
      preLoaderRoute: typeof AuthenticatedAdminFinancialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/inter-pix': {
      id: '/api/public/webhooks/inter-pix'
      path: '/api/public/webhooks/inter-pix'
      fullPath: '/api/public/webhooks/inter-pix'
      preLoaderRoute: typeof ApiPublicWebhooksInterPixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/$id/wallet': {
      id: '/_authenticated/clients/$id/wallet'
      path: '/wallet'
      fullPath: '/clients/$id/wallet'
      preLoaderRoute: typeof AuthenticatedClientsIdWalletRouteImport
      parentRoute: typeof AuthenticatedClientsIdRoute
    }
    '/_authenticated/clients/$id/social/$profileId': {
      id: '/_authenticated/clients/$id/social/$profileId'
      path: '/social/$profileId'
      fullPath: '/clients/$id/social/$profileId'
      preLoaderRoute: typeof AuthenticatedClientsIdSocialProfileIdRouteImport
      parentRoute: typeof AuthenticatedClientsIdRoute
    }
  }
}

interface AuthenticatedClientsIdRouteChildren {
  AuthenticatedClientsIdWalletRoute: typeof AuthenticatedClientsIdWalletRoute
  AuthenticatedClientsIdSocialProfileIdRoute: typeof AuthenticatedClientsIdSocialProfileIdRoute
}

const AuthenticatedClientsIdRouteChildren: AuthenticatedClientsIdRouteChildren =
  {
    AuthenticatedClientsIdWalletRoute: AuthenticatedClientsIdWalletRoute,
    AuthenticatedClientsIdSocialProfileIdRoute:
      AuthenticatedClientsIdSocialProfileIdRoute,
  }

const AuthenticatedClientsIdRouteWithChildren =
  AuthenticatedClientsIdRoute._addFileChildren(
    AuthenticatedClientsIdRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRouteWithChildren
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRouteWithChildren,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminFinancialRoute: typeof AuthenticatedAdminFinancialRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminFinancialRoute: AuthenticatedAdminFinancialRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClientPortalRouteRouteChildren {
  ClientPortalWalletRoute: typeof ClientPortalWalletRoute
  ClientPortalIndexRoute: typeof ClientPortalIndexRoute
}

const ClientPortalRouteRouteChildren: ClientPortalRouteRouteChildren = {
  ClientPortalWalletRoute: ClientPortalWalletRoute,
  ClientPortalIndexRoute: ClientPortalIndexRoute,
}

const ClientPortalRouteRouteWithChildren =
  ClientPortalRouteRoute._addFileChildren(ClientPortalRouteRouteChildren)

interface AuthRouteChildren {
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSetPasswordRoute: AuthSetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClientPortalRouteRoute: ClientPortalRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicWebhooksInterPixRoute: ApiPublicWebhooksInterPixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
