/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns.new'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated/campaigns.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clients'
    | '/settings'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/clients/$id'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/clients'
    | '/settings'
    | '/'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/clients/$id'
    | '/campaigns'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clients'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/campaigns/new'
    | '/_authenticated/clients/$id'
    | '/_authenticated/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
