// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

function isSupabaseAccessToken(value: string | undefined): value is string {
  return typeof value === "string" && value.split(".").length === 3;
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession();
    let token = data.session?.access_token;
    let clearedInvalidSession = false;

    if (token && !isSupabaseAccessToken(token)) {
      await supabase.auth.signOut();
      token = undefined;
      clearedInvalidSession = true;
    }

    if (token) {
      const { error } = await supabase.auth.getUser(token);
      if (error) {
        const refreshed = await supabase.auth.refreshSession();
        data = refreshed.data;
        token = data.session?.access_token;

        if (!token || !isSupabaseAccessToken(token) || refreshed.error) {
          await supabase.auth.signOut();
          token = undefined;
          clearedInvalidSession = true;
        }
      }
    }

    if (clearedInvalidSession) {
      throw new Error("Sessão inválida ou expirada. Entre novamente.");
    }

    return next({
      headers: isSupabaseAccessToken(token) ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
