// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import {
  firstValidSupabaseValue,
  isLikelySupabasePublishableKey,
  isLikelySupabaseUrl,
} from "./config";
import type { Database } from "./types";

type SupabaseAuthUser = { id: string } & Record<string, unknown>;

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // API keys are not user bearer tokens. Keep them in `apikey` only.
    if (headers.get("Authorization") === `Bearer ${supabaseKey}`) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

async function getUserFromSupabaseAuth(
  supabaseUrl: string,
  supabasePublishableKey: string,
  token: string,
): Promise<{
  user: SupabaseAuthUser | null;
  error?: { name?: string; message?: string; status?: number };
}> {
  const response = await fetch(`${supabaseUrl.replace(/\/$/, "")}/auth/v1/user`, {
    method: "GET",
    headers: {
      apikey: supabasePublishableKey,
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok) {
    let message = response.statusText;
    try {
      const payload = (await response.json()) as {
        msg?: unknown;
        message?: unknown;
        error?: unknown;
      };
      message = String(payload.msg ?? payload.message ?? payload.error ?? response.statusText);
    } catch {
      // Keep statusText when the auth service returns a non-JSON error.
    }

    return {
      user: null,
      error: {
        name: "SupabaseAuthUserError",
        message,
        status: response.status,
      },
    };
  }

  const user = (await response.json()) as SupabaseAuthUser;
  return { user };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = firstValidSupabaseValue(
      [process.env.SUPABASE_URL, import.meta.env.VITE_SUPABASE_URL],
      isLikelySupabaseUrl,
    );
    const SUPABASE_PUBLISHABLE_KEY = firstValidSupabaseValue(
      [process.env.SUPABASE_PUBLISHABLE_KEY, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY],
      isLikelySupabasePublishableKey,
    );

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");
    const token = authHeader?.startsWith("Bearer ")
      ? authHeader.slice("Bearer ".length).trim()
      : undefined;

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { user, error } = await getUserFromSupabaseAuth(
      SUPABASE_URL,
      SUPABASE_PUBLISHABLE_KEY,
      token,
    );
    if (error || !user) {
      console.warn("[auth-middleware] Supabase rejected bearer token", {
        errorName: error?.name,
        errorMessage: error?.message,
        errorStatus: error?.status,
      });
      throw new Error("Unauthorized: Invalid token");
    }

    if (!user.id) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: user.id,
        user,
      },
    });
  },
);
