// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import {
  firstValidSupabaseValue,
  isLikelySupabasePublishableKey,
  isLikelySupabaseUrl,
  type SupabaseRuntimeConfig,
} from "./config";
import type { Database } from "./types";

declare global {
  interface Window {
    __PUBGROWTH_SUPABASE_CONFIG__?: SupabaseRuntimeConfig;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // API keys are not user bearer tokens. Keep them in `apikey` only.
    if (headers.get("Authorization") === `Bearer ${supabaseKey}`) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function getRuntimeSupabaseConfig() {
  return typeof window !== "undefined" ? window.__PUBGROWTH_SUPABASE_CONFIG__ : undefined;
}

function createSupabaseClient() {
  const runtimeConfig = getRuntimeSupabaseConfig();
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = firstValidSupabaseValue(
    [
      runtimeConfig?.supabaseUrl,
      import.meta.env.VITE_SUPABASE_URL,
      typeof process !== "undefined" ? process.env.SUPABASE_URL : undefined,
    ],
    isLikelySupabaseUrl,
  );
  const SUPABASE_PUBLISHABLE_KEY = firstValidSupabaseValue(
    [
      runtimeConfig?.supabasePublishableKey,
      import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
      typeof process !== "undefined" ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined,
    ],
    isLikelySupabasePublishableKey,
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
